name: Verify

on:
  push:
    paths:
      - 'src/**'
      - 'external/**'
      - 'msvc/**'
  workflow_dispatch:
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./msvc\UnrealBuildConfigurator.sln

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        build-platform: ["x86", "x64"]
        build-configuration: ["Debug", "Release"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Setup MSVC Developer console
#      uses: ilammy/msvc-dev-cmd@v1
#      with:
#        arch: ${{ matrix.build-platform }}
#        vsversion: "2019"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - run: dir
    - run: dir msvc\

    - name: Build
      run: msbuild /p:Configuration=${{ matrix.build-configuration }} /p:Platform=${{ matrix.build-platform }} ${{ env.SOLUTION_FILE_PATH }}
