name: Verify Build

on:
  push:
    paths:
      - 'src/**'
      - 'external/**'
      - 'msvc/**'
  workflow_dispatch:
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\msvc\UnrealBuildConfigurator.sln

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        build-platform: ["x86", "x64"]
        build-configuration: ["Debug", "Release"]
    steps:
    - name: Build
      id: build
      uses: ./.github/actions/build
      with:
        platform: ${{ matrix.build-platform }}
        configuration: ${{ matrix.build-configuration }}
        solution-path: ${{ env.SOLUTION_FILE_PATH }}
        
